IF NOT EXISTS CREATE TABLE schema_migrations (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL UNIQUE,
    executed_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

IF NOT EXISTS CREATE TABLE twitch_users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    twitch_id VARCHAR(50) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL,
    display_name VARCHAR(50),
    access_token TEXT,
    refresh_token TEXT,
    expires_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    INDEX idx_stream_start (start_at)
);